config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/contact' => 'static_pages#contact'

  get '/about' => 'static_pages#about'

  get '/help' => 'static_pages#help'

  get '/logout' => 'user_sessions#destroy'
  get '/login' => 'user_sessions#new'

  get '/ride_transactions/getRideData/:id' => 'ride_transactions#getRideData'

  get '/ride_transactions/search' => 'ride_transactions#search'

  resources :users do
    member do
      get :following, :followers
    end
    get 'search', on: :collection
  end

  resource :account, :controller => "users" do
    member do
      get :following, :followers
    end
  end
  
  resource :user_session, only: [:create, :new, :destroy]  
  resources :rides
  resources :ride_transactions
  resources :relationships, only: [:create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base  
	has_many :rides
	has_many :ride_transactions
	has_many :active_relationships, class_name:  "Relationship",
		foreign_key: "follower_id", dependent: :destroy

    has_many :passive_relationships, class_name:  "Relationship",
		foreign_key: "followed_id", dependent: :destroy

    has_many :following, through: :active_relationships, source: :followed
    has_many :followers, through: :passive_relationships, source: :follower

	acts_as_authentic 
	self.per_page = 15

	# Follows a user.
	def follow(other_user)
	    active_relationships.create(followed_id: other_user.id)
	end

	# Unfollows a user.
	def unfollow(other_user)
		active_relationships.find_by(followed_id: other_user.id).destroy
	end

	# Returns true if the current user is following the other user.
	def following?(other_user)
		following.include?(other_user)
	end

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, only: [:new, :create]
  before_filter :require_user, only: [:show, :edit, :update, :following, :followers]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:info] = "Account registered!"
      redirect_back_or_default account_url
    else
      render 'new'
    end
  end
  
  def show
    @user = params[:id] ? User.find(params[:id]) : current_user
  end

  def index
    @title = "Users"
    @users = User.page(params[:page]) 
    # @users = User.where(isactive: true)
  end

  def search
    @title = "Search user"
    @search = params[:search]
    @users = User.where(["name like :t", {t: "%#{@search}%"}]).page(params[:page])
    render 'index'
  end

  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update_attributes(user_params)
      flash[:info] = "Account updated!"
      redirect_to account_url
    else
      render 'edit'
    end
  end

  def following
    @title = "Following"
    @user  = params[:id] ? User.find(params[:id]) : current_user
    @users = @user.following.paginate(page: params[:page], per_page: 7) 
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = params[:id] ? User.find(params[:id]) : current_user
    @users = @user.followers.paginate(page: params[:page], per_page: 7) 
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user,size)
	    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
	    image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/users/_follow.html.erb
<div class="large-3 large-offset-3">
	<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
		<%= hidden_field_tag :followed_id, @user.id %>
		<%= f.submit "Follow", class: "button success tiny follow_unfollow" %>
	<% end %>
</div>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
	<div id="follow_form" class="row margin-top margin-bottom">
		<% if current_user.following?(@user) %>
			<%= render 'unfollow' %>
		<% else %>
			<%= render 'follow' %>
		<% end %>
	</div>
<% end %>

app/views/users/_form.html.erb
<%= form_for user do |f| %>
	<%= render 'layouts/error_messages', object: user %>

	<%= content_tag :div, class: "row" do %>
		<%= content_tag :div, class: "large-10" do %>
			<%= f.label :name %>
			<%= f.text_field :name, required: true  %>
		<% end %>
	<% end %>

	<%= content_tag :div, class: "row" do %>
		<%= content_tag :div, class: "large-10" do %>
			<%= f.label :email %>
			<%= f.email_field :email, required: true  %>
		<% end %>
	<% end %>

	<% if user.new_record? %>
		<%= content_tag :div, class: "row" do %>
			<%= content_tag :div, class: "large-10" do %>
				<%= f.label :password %>
				<%= f.password_field :password, required: true  %>
			<% end %>
		<% end %>

		<%= content_tag :div, class: "row" do %>
			<%= content_tag :div, class: "large-10" do %>
				<%= f.label :password_confirmation, "Confirm Password" %>
				<%= f.password_field :password_confirmation, required: true  %>
			<% end %>
		<% end %>
	<% end %>
	<%= content_tag :div, class: "row" do %>
		<%= content_tag :div, class: "large-10" do %>
			<%= f.submit (user.new_record? ? "Register" : "Update Profile"), class: "tiny radius button" %>
		<% end %>
	<% end %>
<% end %>

app/views/users/_stats.html.erb
<div class="row">
	<div class="row">
		<div class="columns large-8 large-offset-1"><%= link_to "Following", following_user_path(@user.id) %></div>
		<div id="followings" class="columns large-3"><%= @user.following.count %></div>
	</div>

	<div class="row">
		<div class="columns large-8 large-offset-1"><%= link_to "Followers", followers_user_path(@user.id) %></div>
		<div id="followers" class="columns large-3"><%= @user.followers.count %></div>
	</div>
</div>

app/views/users/_unfollow.html.erb
<div class="large-3 large-offset-3">
	<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
         html: { method: :delete }, remote: true) do |f| %>
		<%= f.submit "Unfollow", class: "button alert tiny follow_unfollow" %>
	<% end %>
</div>

app/views/users/_user.html.erb
<%= gravatar_for user, size %>	
<strong><%= user.name %></strong>

app/views/users/edit.html.erb
<% content_for :title, @user.name %>
<% content_for :heading, "Settings- " + @user.name %>
<div class="row top-margin">
	<div class="columns large-3 large-offset-1">
		<%= render 'form', user: @user %>
	</div>
	<div class="columns large-8">
		<%= gravatar_for @user, 100 %>
		<a href="https://gravatar.com/emails" target="_blank">change</a>
	</div>
</div>

app/views/users/index.html.erb
<!-- add link to profiles, follow-unfollow links. notifications from followed users to be followed from there. -->
<% content_for :title, @title %>
<% content_for :heading, @title %>
<div class="row margin-top">
	<div class="columns large-12">
		<% if @users[0] %>
			<div class="row">
				<div class="columns large-6 level">
					<%= will_paginate @users, renderer: FoundationPagination::Rails %>
				</div>
				<div class="columns large-3 end">
					<% if @users.length > 10 %>
						<%= form_tag search_users_path, method: 'get' do %>
						    <%= text_field_tag 'search', nil, placeholder: "Search", class: "round" %>
						<% end %>
					<% end %>
				</div>
			</div>
			<ul class="users no-bullet">
				<% @users.each do |user| %>
					<li><%= link_to (render 'user', size: 75, user: user), user %></li>
				<% end %>
			</ul>
			<%= will_paginate @users, renderer: FoundationPagination::Rails %>
		<% else %>	
			<div class="panel callout large-6 large-centered">
				'<%= @search %>' not found.
			</div>
		<% end %>
	</div>
</div>

app/views/users/new.html.erb
<% content_for :title, "Signup" %>
<% content_for :heading, "Signup" %>
<div class="row">
	<div class="columns large-5 large-offset-2">
		<%= render 'form', user: @user %>
	</div>	
</div>

app/views/users/show.html.erb
<% content_for :title, @user.name %>
<% content_for :heading, "Profile - " + @user.name %>
<div class="row margin-top">
	<div class="columns large-4 panel callout">
	    <div class="row">
	      <div class="columns large-11 large-offset-1">
	        <%= link_to (render 'user', size: 75, user: @user), @user %>
	        <%= render 'follow_form' if current_user %>
	      </div>
	    </div> <hr>
	    <div class="row">
	      <%= render 'users/stats' %>
	    </div>
	</div>

	<div class="columns large-4 large-offset-2">
		<div class="callout panel radius">
			<p class="text-center panel-heading"> RideShare Statistics - User </p>
			<%= render 'rides/stats' %> <hr>
			<%= render 'ride_transactions/stats' %>
		</div>
	</div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row margin-top">
  <div class="columns large-4 panel callout">
    <div class="row">
      <div class="columns large-11 large-offset-1">
        <%= link_to (render 'user', size: 75, user: @user), @user %>
      </div>
    </div> <hr>
    <div class="row">
      <%= render 'stats' %>
    </div>
  </div>

  <div class="columns large-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users no-bullet">
        <% @users.each do |user| %>
          <li><%= link_to (render 'user', size: 50, user: user), user %></li>
        <% end %>
      </ul>
      <%= will_paginate @users, renderer: FoundationPagination::Rails %>
    <% end %>
  </div>
</div>