config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/contact' => 'static_pages#contact'

  get '/about' => 'static_pages#about'

  get '/help' => 'static_pages#help'

  get '/logout' => 'user_sessions#destroy'
  get '/login' => 'user_sessions#new'

  get '/ride_transactions/getRideData/:id' => 'ride_transactions#getRideData'

  get '/ride_transactions/search' => 'ride_transactions#search'

  resources :users do
    member do
      get :following, :followers
    end
    get 'search', on: :collection
  end

  resource :account, :controller => "users" do
    member do
      get :following, :followers
    end
  end
  
  resource :user_session, only: [:create, :new, :destroy]  
  resources :rides
  resources :ride_transactions
  resources :relationships, only: [:create, :destroy]

end

app/models/ride.rb
class Ride < ActiveRecord::Base

	belongs_to :user
	has_many :ride_transactions

	validates :from_address, presence: true
	validates :to_address, presence: true
	validates :user_id, presence: true
	
	validates :from_latitude, numericality: true
	validates :from_longitude, numericality: true
	validates :to_latitude, numericality: true
	validates :to_longitude, numericality: true

	validates :car_description, presence: true, length: { maximum: 100 }
	validates :seats_available, numericality: { only_integer: true, less_than_or_equal_to: 10, 
												greater_than: 0 }
	validates :seats_remaining, numericality: { only_integer: true, less_than_or_equal_to: 10, 
				greater_than_or_equal_to: 0 }
	
	validate :validate_timeofride
	
	before_validation :update_ride_seats_remaining

	private
		def validate_timeofride
			if (timeofride.to_time < (0.5).hour.from_now)
				return false
			end
		end

		def update_ride_seats_remaining
			self.seats_remaining = self.seats_available - 
					self.ride_transactions.where(["isactive = :t", {t: true}]).count
		end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  
  before_filter :require_user
  before_filter :correct_user, only: [:edit, :destroy, :update]

  def new
    @ride = Ride.new
  end

  def create
    @ride = current_user.rides.build(ride_params)
    if @ride.save
      flash[:info] = "Ride registered!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @ride = Ride.find_by_id(params[:id])
    if @ride && @ride.isactive
      @ride_transactions = @ride.ride_transactions.where("isactive = :v", {v: true})
      render 'show'
    else
      render file: 'public/404.html', status: 404
    end
  end

  def edit
    @ride = Ride.find_by_id(params[:id])
    if not @ride.isactive 
      render file: 'public/404.html', status: 404
    elsif @ride.timeofride < Time.now
      flash[:info] = "This ride has already been completed!"
      redirect_to root_path
    end
  end

  def update
    @ride = Ride.find_by_id(params[:id])
    if @ride.update_attributes(ride_params)
      flash[:info] = "Ride updated!"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def index
    @rides = rides current_user.id
    @inactive_rides = inactive_rides current_user.id
  end

  def destroy
    @ride = Ride.find(params[:id])
    if @ride.timeofride < Time.now
      flash[:info] = "This ride has already been completed!"
      redirect_to rides_path
    elsif @ride.update_attribute("isactive", false)
      @ride.ride_transactions.update_all(isactive: false)
      respond_to do |format|
        format.html { redirect_to rides_path, info: "Ride canceled successfully." }
        format.js 
      end
    else
      #render text: "hello world"
    end
  end

  private

    def ride_params
      params.require(:ride).permit(:from_address, :to_address, :timeofride, 
        :car_description, :seats_available, :from_latitude, :to_latitude, :from_longitude,
        :to_longitude)
    end

    def correct_user
      ride = Ride.find_by_id(params[:id])
      if ride.nil? || current_user.id != ride.user_id
        flash[:notice] = "You do not have access to this page"
        redirect_to root_path
        return false
      end
    end
end

app/helpers/rides_helper.rb
module RidesHelper
	def rides_count
    Ride.where(["isactive = :t",{t: true}]).count
  end

  # Refactor these as model methods
  def inactive_count(userid = nil)
    	if userid
    		Ride.where(["isactive = :t and user_id = :u",
        		{t: false, u: userid}]).count
    	else
    		Ride.where(["isactive = :t", {t: false}]).count
    	end
  end

  def future_count(userid = nil)
  	if userid
    		Ride.where(["isactive = :t and user_id = :u and timeofride > :v", 
        		{t: true, u: userid, v: Time.now}]).count
    	else
    		Ride.where(["isactive = :t and timeofride > :u", 
    			{t: true, u: Time.now}]).count
    	end
  end

  def completed_count(userid = nil)
  	if userid
    		Ride.where(["isactive = :t and user_id = :u and timeofride < :v", 
  	  		{t: true, u: userid, v: Time.now}]).count
    	else
    		Ride.where(["isactive = :t and timeofride < :u", 
    			{t: true, u: Time.now}]).count
    	end
  end
end

app/views/rides/_form.html.erb
<div class="row">
	<div id="box-alert" class="alert-box columns large-8 large-centered info" style="visibility:hidden;" data-alert>
		<span id="alert-text" class="subheader"></span>
	</div>
	
</div>
<div class="row">
	<div class="large-6 columns">
	<%= form_for @ride do |f| %>
		<%= render 'layouts/error_messages', object: @ride %>

		<%= content_tag :div, class: "row" do %>
			<%= content_tag :div, class: "large-10 columns" do %>
				<%= f.label :from_address %>
				<%= f.text_field :from_address, required: true %>
			<% end %>
		<% end %>

		<%= content_tag :div, class: "row" do %>
			<%= content_tag :div, class: "large-10 columns" do %>
				<%= f.label :to_address %>
				<%= f.text_field :to_address, required: true %>
			<% end %>
		<% end %>

		<%= content_tag :div, class: "row" do %>
			<%= content_tag :div, class: "large-10 columns" do %>
				<%= f.label :timeofride %>
				<%= f.text_field :timeofride, autocomplete: "off", class: "datetimepicker", required: true, readonly: true, value: (@ride.timeofride) ? @ride.timeofride.to_time.strftime("%d-%m-%Y %H:%M") : "" %>
			<% end %>
		<% end %>

		<%= content_tag :div, class: "row" do %>
			<%= content_tag :div, class: "large-10 columns" do %>
				<%= f.label :car_description, "Car Description", required: true %>
				<%= f.text_area :car_description %>
			<% end %>
		<% end %>

		<%= content_tag :div, class: "row" do %>
			<%= content_tag :div, class: "large-10 columns" do %>
				<%= f.label :seats_available, "# of Passenger seats available" %>
				<%= f.number_field :seats_available, max: "10", min: "1", required: true %>
			<% end %>
		<% end %>

		<%= content_tag :div, class: "row" do %>
			<%= content_tag :div, class: "large-10 columns" do %>
				<%= f.submit (@ride.new_record? ? "Register" : "Update Ride"), class: "tiny radius button", disabled: true %>
				<button type="button" disabled class="button radius tiny" id="updateMarkers">Update Markers </button>
				<button type="button" disabled id="getRoute" class="button radius tiny">Get Route</button>
			<% end %>
		<% end %>
		<%= f.hidden_field :from_latitude %>
		<%= f.hidden_field :from_longitude %>
		<%= f.hidden_field :to_latitude %>
		<%= f.hidden_field :to_longitude %>
	<% end %>
	</div>
	<div class="large-6 columns margin-top">
		<div id="map" style='width: 600px; height: 400px;'></div>
	</div>
</div>

<script type="text/javascript">
	var bounds = [];

	// initialize map
	var map = new GMaps({
		div: '#map',
        lat: <%= @ride.from_latitude ? @ride.from_latitude : 13.0826802 %>,
        lng: <%= @ride.from_longitude ? @ride.from_longitude : 80.27071840000008 %>
	});

	//update address on 'drag-end'
	//change by using 2 constant markers and updating them only on dragend
	function updateAddress(marker, element)
	{
		GMaps.geocode({
			latLng: marker.getPosition(),
			callback: function(results, status) {

				var text = (element == "#ride_from_address") ? "From: " : "To: ";
				
				if (status == 'OK') {
					marker.infoWindow.close();
					marker.infoWindow = new google.maps.InfoWindow({
					  	content: text + results[0].formatted_address
					});
					marker.infoWindow.open(marker.get('map'), marker);
					var latlng = results[0].geometry.location;
					$(element).val(results[0].formatted_address);
					if(element == "#ride_to_address")
					{
						$("#ride_to_latitude").val(latlng.lat());
			      		$("#ride_to_longitude").val(latlng.lng());
					}
					else
					{
						$("#ride_from_latitude").val(latlng.lat());
			      		$("#ride_from_longitude").val(latlng.lng());
					}
				}
				if($("#updateMarkers").attr("disabled"))
					$("#updateMarkers").removeAttr("disabled");
				if($("#getRoute").attr("disabled"))
					$("#getRoute").removeAttr("disabled");	
			}
		});
	}

	//to fit markers after they're loaded

	function fitToBounds(bounds){
		map.fitLatLngBounds(bounds);
		$("input[type='submit']").removeAttr("disabled");
		$("#box-alert").css("visibility","hidden");
	}

	//if new ride, use geolocation

	<% if @ride.new_record? %>
		GMaps.geolocate({
			success: function(position) {
				map.setCenter(position.coords.latitude, position.coords.longitude);
				//bounds.push(new google.maps.LatLng(position.coords.latitude, position.coords.latitude))
				$("#alert-text").html("Location determined! Add addresses and update markers to view them on map. You can move them around too!");
			},
			error: function(error) {
				$("#alert-text").html('Geolocation failed: '+error.message +". Add addresses and update markers to view them on map. You can move them around too!");
			},
			not_supported: function() {
				$("#alert-text").html("Allow the site to 'Auto-detect' your location or Add addresses and update markers to view them on map. You can move them around too!");
			},
			always: function() {
				$("#alert-text").append("<br>PS: Kindly update markers to avoid outdated data submission.")
				$("#box-alert").css("visibility","initial");
			}
		});
	<% end %>

	//if edit, use existing locations to fill map with markers
	
	<% unless @ride.new_record? %>
		map.addMarker({
	        lat: <%= @ride.from_latitude %>,
	        lng: <%= @ride.from_longitude %>,
			infoWindow: {
				content: 'From: <%= @ride.from_address %>'
			},
  			draggable: true,
			dragend: function(e) {
				updateAddress(this, "#ride_from_address");
			}
		});
		map.addMarker({
	        lat: <%= @ride.to_latitude %>,
	        lng: <%= @ride.to_longitude %>,
			infoWindow: {
				content: 'To: <%= @ride.to_address %>'
			},
  			draggable: true,
			dragend: function(e) {
				updateAddress(this, "#ride_to_address");
			}
		});
		
		bounds.push(new google.maps.LatLng(<%= @ride.from_latitude %>, <%= @ride.from_longitude %>));
		bounds.push(new google.maps.LatLng(<%= @ride.to_latitude %>, <%= @ride.to_longitude %>));
		map.fitLatLngBounds(bounds);
		$("#alert-text").append("Kindly update markers to avoid outdated data submission.");
		$("#box-alert").css("visibility","initial");
		$("input[type='submit']").removeAttr("disabled");
	<% end %>

	//before submit, update markers - waste of API calls

	// $("#new_ride").on('submit',function(){
		
	// });

	$("#ride_from_address, #ride_to_address").change(function(){
		if($("#updateMarkers").attr("disabled"))
			$("#updateMarkers").removeAttr("disabled");
		if($("#getRoute").attr("disabled"))
			$("#getRoute").removeAttr("disabled");	
	});

	//update the markers

	$("#updateMarkers").click(function(){
		if($('#ride_from_address').val() && $('#ride_to_address').val())
		{
			bounds.length = 0; //clear the array
			map.removeMarkers(); //clear the map
			
			GMaps.geocode({
			  address: $('#ride_from_address').val(),
			  callback: function(results, status) {
			    
			    if (status == 'OK') {
			      var latlng = results[0].geometry.location;
			      bounds.push(new google.maps.LatLng(latlng.lat(), latlng.lng()));
			      
			      $("#ride_from_latitude").val(latlng.lat());
			      $("#ride_from_longitude").val(latlng.lng());
			      
			      map.addMarker({
			        lat: latlng.lat(),
			        lng: latlng.lng(),
					infoWindow: {
						content: "From:" + $("#ride_from_address").val()
					},
		  			draggable: true,
					dragend: function(e) {
						updateAddress(this, "#ride_from_address");
					}
			      });
			    }

			    // fit markers after callback
		        fitToBounds(bounds);
			  }
			});

			GMaps.geocode({
			  address: $('#ride_to_address').val(),
			  callback: function(results, status) {
			    
			    if (status == 'OK') {
			      var latlng = results[0].geometry.location;
			      bounds.push(new google.maps.LatLng(latlng.lat(), latlng.lng()));
			      
			      $("#ride_to_latitude").val(latlng.lat());
			      $("#ride_to_longitude").val(latlng.lng());
			      
			      map.addMarker({
			        lat: latlng.lat(),
			        lng: latlng.lng(),
					infoWindow: {
						content: "To:" + $("#ride_to_address").val()
					},
		  			draggable: true,
					dragend: function(e) {
						updateAddress(this, "#ride_to_address");
					}
			      });
			    }

			    // fit markers after callback
		        fitToBounds(bounds);
			  }
			});
		$("#getRoute").removeAttr("disabled");
		}
		else
		{
			$("#alert-text").html("From and To address are required for markers to be updated on the Map.");
			$("#box-alert").css("visibility","initial");
		}
	});
	$("#getRoute").click(function(){
		var path = [];
		
		if(map.polylines.length)
        	map.removePolylines();

        map.getRoutes({
            origin: [$("#ride_from_latitude").val(), $("#ride_from_longitude").val()],
			destination: [$("#ride_to_latitude").val(), $("#ride_to_longitude").val()],
			callback: function (e) {
                for (i=0; i<e[0].legs.length; i++) {
                    for(j=0; j<e[0].legs[i].steps.length; j++) {
                    	for(k=0; k<e[0].legs[i].steps[j].path.length; k++) {
                    		path.push(e[0].legs[i].steps[j].path[k]);
                    	}
                    }
                }
                map.drawPolyline({
					path: path,
					strokeColor: '#131540',
					strokeOpacity: 0.6,
					strokeWeight: 6
				});  
            }
        });
	});
</script>

app/views/rides/_ride.html.erb
<div class="callout panel radius <%= "disabled-ride" unless ride.isactive %>">
	<% if ride.isactive %>
		<% if current_user && ride.user_id == current_user.id %>
			<% if ride.timeofride > Time.now %>
				<%= link_to fa_icon("minus-circle"), ride, class: "ride-delete right", method: :delete, remote: true %>
				<%= link_to fa_icon("pencil"), edit_ride_path(ride), class: "right edit margin-right" %>
			<% else %>
				<%= link_to fa_icon("check"), "#", class: "right margin-right" %>
			<% end %>
		<% end %>
	<% else %>
		<%= fa_icon("trash", class: "right margin-right") %>
	<% end %>
	<p class="text-center panel-heading">
		<%= fa_icon "clock-o" %>
		<%= ride.timeofride.to_time.strftime("%A, %d-%m-%Y %H:%M, %Z") %>
	</p>
	<%= render 'layouts/ride_information', ride: ride %>
	<%= render 'layouts/ride_footer', ride: ride %>
</div>

app/views/rides/_stats.html.erb
<div class="row">
	<div class="row">
		<div class="columns large-8 large-offset-1"><%= link_to "Total Rides Posted", "#"%></div>
		<div id="totalCount" class="columns large-3"><%= inactive_count(current_user.id) + completed_count(current_user.id) + future_count(current_user.id) %></div>
	</div>
	<div class="row">
		<div class="columns large-8 large-offset-1"><%= link_to "Completed Posted Rides", "#"%> </div>
		<div id="completedCount" class="columns large-3"><%= completed_count(current_user.id) %> </div>
	</div>
	<div class="row">
		<div class="columns large-8 large-offset-1"><%= link_to "Cancelled Posted Rides", "#"%> </div>
		<div id="inactiveCount" class="columns large-3"><%= inactive_count(current_user.id) %> </div>
	</div>
	<div class="row">
		<div class="columns large-8 large-offset-1"><%= link_to "Future Posted Rides", "#"%> </div>
		<div id="futureCount" class="columns large-3"><%= future_count(current_user.id) %></div>
	</div>
</div>

app/views/rides/destroy.js.erb
<% if (completed_count(current_user.id) + future_count(current_user.id)) == 0 %>
	$("body").html("<script>window.location = '<%= rides_path %>'</script>")
<% else %>
	$("#totalCount").html('<%= (inactive_count(current_user.id) + completed_count(current_user.id) + future_count(current_user.id)) %>');
	$("#completedCount").html('<%= completed_count(current_user.id) %>');
	$("#inactiveCount").html('<%= inactive_count(current_user.id) %>');
	$("#futureCount").html('<%= future_count(current_user.id) %>');
<% end %>

app/views/rides/edit.html.erb
<% content_for :title, "Modify Ride" %>
<% content_for :heading, "Modify Ride" %>
<%= render 'form' %>

app/views/rides/index.html.erb
<% content_for :title, "My Rides" %>
<% content_for :heading, "My Rides" %>
<div class="row margin-top">
	<% if @rides.length == 0 && @inactive_rides.length == 0 %>
		<div class="columns large-6 large-centered">
			<div class="callout panel radius">
				<p class="text-center"> Snap! </p>
				You have not posted a ride, YET! There's always a first time.., <%= link_to "Post Ride", new_ride_path %>
			</div>
		</div>
	<% else %>
		<div class="columns large-4">
			<div class="callout panel radius">
				<p class="text-center panel-heading"> RideShare Statistics - Posts </p>
				<%= render 'stats' %>
			</div>
		</div>
		
		<div class="columns large-7 page large-offset-1">
			<% if @rides.length %>
				<% @rides.each do | ride | %>
					<%= render 'ride', ride: ride %>
				<% end %>
			<% end %>

			<% if @inactive_rides.length %>
				<% @inactive_rides.each do | inactive_ride | %>
					<%= render 'ride', ride: inactive_ride %>
				<% end %>
			<% end %>
		</div>
	<% end %>
</div>

app/views/rides/new.html.erb
<% content_for :title, "Post Ride" %>
<% content_for :heading, "Post a Ride" %>
<%= render 'form' %>

app/views/rides/show.html.erb
<% content_for :title, "Ride" %>
<% content_for :heading, "Ride Information:" %>
<div class="row margin-top">
	<% if @ride_transactions.length == 0 %>
		<div class="columns large-6 large-centered">
			<div class="callout panel radius">
				<p class="text-center"> Snap! </p>
					Nobody has shared your ride yet. Kindly check back after sometime on any updates.
			</div>
		</div>
	<% else %>
		<div class="columns large-7">
			<div class="callout panel radius">
				<p class="text-center panel-heading"> RideShare Statistics - Ride </p>
				<div class="row">
					<div class="row">
						<div class="columns large-3 large-offset-1"><%= link_to "Shares", ""%> </div>
						<div id="futureCount" class="columns large-8"><%= @ride_transactions.length %></div>
					</div>
				</div>
				<%= render 'layouts/ride_information', ride: @ride %>
			</div>
		</div>
		
		<div class="columns large-5 page">
			<% @ride_transactions.each do | ride_transaction | %>
				<div class="panel callout radius">
					<p class="text-center panel-heading">
						<%= fa_icon "clock-o" %>
						<%= ride_transaction.timeofride.to_time.strftime("%A, %d-%m-%Y %H:%M, %Z") %>
					</p>
					<%= render 'layouts/ride_transaction_information', ride_transaction: ride_transaction %>
					<span class="right margin-right">
						Opted by: <%= link_to ride_transaction.user.name, ride_transaction.user %>
					</span>
				</div>
			<% end %>
		</div>
	<% end %>
</div>