config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/contact' => 'static_pages#contact'

  get '/about' => 'static_pages#about'

  get '/help' => 'static_pages#help'

  get '/logout' => 'user_sessions#destroy'
  get '/login' => 'user_sessions#new'

  get '/ride_transactions/getRideData/:id' => 'ride_transactions#getRideData'

  get '/ride_transactions/search' => 'ride_transactions#search'

  resources :users do
    member do
      get :following, :followers
    end
    get 'search', on: :collection
  end

  resource :account, :controller => "users" do
    member do
      get :following, :followers
    end
  end
  
  resource :user_session, only: [:create, :new, :destroy]  
  resources :rides
  resources :ride_transactions
  resources :relationships, only: [:create, :destroy]

end

app/views/layouts/_error_messages.html.erb
<!-- Customize error messages using I18n. Eg: login/register -->
<% if object.errors.any? %>
	<ul class="error-container panel callout">
		<% object.errors.messages.each do |key,msgs| %>
			<% msgs.each do |msg| %>
    			<li><%= msg %></li>
    		<% end %>
	  <% end %>
	</ul>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
	<p class="text-center">
		&copy;<%= Time.now.year %> , <%= link_to "Ritikesh G", "#" %>
	</p>
	<p class="text-center"> 
		<%= link_to "Contact", contact_path %> | 
		<%= link_to "About", about_path %> | 
		<%= link_to "Help", help_path %>
	</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="sticky">
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1>
            <%= link_to fa_icon("home 3x"), root_path, class: "item" %>
          </h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
      </ul>

      <section class="top-bar-section">
        <ul class="right">
        <% if current_user %>
          <li class="has-dropdown"> 
            <%= link_to fa_icon("bell", text: " Notifications"), "#" %>
            <ul class="dropdown">
            </ul>
          </li>
          <li class="has-dropdown"> 
            <%= link_to fa_icon("share-square-o", text: " RideShare"), "#" %>
            <ul class="dropdown">
              <li> <%= link_to fa_icon("users", text: " Users"), users_path %></li> 

              <li class="divider"> </li>
              
              <li> <%= link_to fa_icon("car", text: " Post Ride"), new_ride_path %></li> 
              <li> <%= link_to fa_icon("list-alt", text: " My Rides"), rides_path %></li> 

              <li class="divider"> </li>
              
              <li> <%= link_to fa_icon("taxi", text: " Book Ride"), new_ride_transaction_path %></li> 
              <li> <%= link_to fa_icon("list", text: " My Bookings"), ride_transactions_path %></li> 
            </ul>
          </li>
          <li class="divider"> </li>
          
          <li class="has-dropdown"> 
            <a href="#"><%= current_user.name %></a>
            <ul class="dropdown">
              <li> <%= link_to fa_icon("user", text: " Account"), account_path %> </li>
              <li> <%= link_to fa_icon("cog spin", text: " Settings"), edit_account_path %> </li>
              <li> <%= link_to fa_icon("sign-out", text: " Logout"), logout_path %> </li>
            </ul>
          </li>
        <% else %>
          <li> <%= link_to fa_icon("user-plus lg", text: " Register"), new_user_path, {title: "Register"} %> </li>
          <li class="divider"> </li>
          <li> <%= link_to fa_icon("sign-in lg", text: " Sign in"), login_path, {title: "Login"} %> </li>
        <% end %>
        </ul>
      </section>
    </nav>
  </div>
</header>

app/views/layouts/_ride_footer.html.erb
<span class="right margin-right">
	<%= link_to ride.user.name, ride.user, class: "ride-footer-text" %> | <%= link_to fa_icon("info-circle"), ride %>
</span>

app/views/layouts/_ride_information.html.erb
<div class="row">
	<div class="row">
		<div class="columns large-3 large-offset-1"><%= link_to "From:", "#"%></div>
		<div class="columns large-8"><%= ride.from_address %></div>
	</div>
	<div class="row">
		<div class="columns large-3 large-offset-1"><%= link_to "To:", "#"%> </div>
		<div class="columns large-8"><%= ride.to_address %> </div>
	</div>
	<div class="row">
		<div class="columns large-3 large-offset-1"><%= link_to "Car Description:", "#"%> </div>
		<div class="columns large-8"><%= ride.car_description %> </div>
	</div>
	<div class="row">
		<div class="columns large-3 large-offset-1"><%= link_to "Seats Specified:", "#"%> </div>
		<div class="columns large-8"><%= ride.seats_available %></div>
	</div>
	<div class="row">
		<div class="columns large-3 large-offset-1"><%= link_to "Seats taken:", "#"%> </div>
		<div class="columns large-8"><%= (ride.seats_available - ride.seats_remaining) %></div>
	</div>
</div>

app/views/layouts/_ride_transaction_information.html.erb
<div class="row">
	<div class="row">
		<div class="columns large-3 large-offset-1"><%= link_to "Pick up:", "#"%></div>
		<div class="columns large-8"><%= ride_transaction.from_address %></div>
	</div>
	<div class="row">
		<div class="columns large-3 large-offset-1"><%= link_to "Drop to:", "#"%> </div>
		<div class="columns large-8"><%= ride_transaction.to_address %> </div>
	</div>
	<div class="row">
		<div class="columns large-3 large-offset-1"><%= link_to "Distance:", "#"%> </div>
		<div class="columns large-8"><%= ride_transaction.distance %> km</div>
	</div>
	<div class="row">
		<div class="columns large-3 large-offset-1"><%= link_to "Cost:", "#"%> </div>
		<div class="columns large-8"><%= ride_transaction.cost %> /- </div>
	</div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= title yield(:title) %></title>
    <%= favicon_link_tag "favicon.ico" %>
    <%= stylesheet_link_tag "application" %>
    
    <% if content_for?(:styles) %>
      <%= yield(:styles) %>
    <% end %>
    
    <%= javascript_include_tag "vendor/modernizr" %>
    <script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=true"> </script>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <% if content_for?(:script) %>
      <%= yield(:script) %>
    <% end %>

    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body> 
    <%= render 'layouts/header' %>
    <% if content_for?(:heading) %>
      <h3><%= yield(:heading) %></h3>
    <% end %>
    <div class="pageload-con"></div>
    <div class="otherload-con hide"></div>
    <% unless flash.empty? %>
      <div class="row">
        <div class="large-6 large-centered columns">
          <% flash.each do |key, value| %>
            <%= content_tag :div, data: { alert: '' }, class: "alert-box #{key}" do %>
              <span><%= value %></span>
              <a href="#" class="close">&times;</a>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>